
import java.awt.Component;
import java.awt.Point;
import java.awt.Graphics2D;
import javax.swing.*;
import java.awt.Graphics;
import java.awt.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jjann
 */
public class Renderer extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Renderer.class.getName());
    Map world;
    int labelNum;
    String[] cityNameArray;
    Point[] cityPoints;
    String[][] adjacencyMatrix;
    int[][] distanceMatrix;
    
    /**
     * Creates new form Renderer
     */
    
    public Renderer() {
        initComponents();
        Clock clock = new Clock(5);
        Map world = new Map();
        

        labelNum = world.cities.length;
        cityNameArray = new String[labelNum];
        cityPoints = new Point[labelNum];
        adjacencyMatrix = world.pathMatrix;
        distanceMatrix = new int[labelNum][labelNum];
        
        for (int i = 0; i < labelNum; i++) {
            cityNameArray[i] = world.cities[i].cityName;
            cityPoints[i] = world.cities[i].coords;
            for (int j = 0; j < labelNum; j++) {
                if(adjacencyMatrix[i][j].indexOf(",") != -1) {
                    distanceMatrix[i][j] = Integer.parseInt(adjacencyMatrix[i][j].substring(0, adjacencyMatrix[i][j].indexOf(",")));
                }
            }
        }
        mapRender();
        
        
        
    }

    public void paintConnections (Graphics g) {
    Graphics2D g2 = (Graphics2D) g;
    for (int i = 0; i < labelNum; i++) {
        for (int j = 0; j < labelNum; j++) {
            if (distanceMatrix[i][j] != 0) {
                 g2.drawLine(cityPoints[i].x, cityPoints[i].y , cityPoints[j].x, cityPoints[j].y);
            }
        }
    }
    
    
}
    
    
    
    public void mapRender() {
        Component[] l = new Component[labelNum];
        
        for (int i = 0; i < labelNum; i++) {
            l[i] = jPanel3.add(new JLabel(cityNameArray[i]));
            System.out.println(cityNameArray[i]);
            l[i].setSize(200, 200);
            l[i].setVisible(true);
            l[i].setLocation(cityPoints[i]);
            
            for (int j = 0; j < labelNum; j++) {
                if(distanceMatrix[i][j] != 0) {
                    
                }
            }
            
            
        }
    }


    
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 153));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Map", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Renderer().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}


